[package]
name = "jdict2"
version = "0.1.0"
edition = "2021"

[profile.release]
lto = 'thin'
panic = 'abort'
debug = false

[dependencies]
compact_str = { version = "0.7.1", features = ["serde"] }
eframe = "0.27.2"
egui = "0.27.2"
flate2 = "1.0.30"
isolang = { version = "2.4.0", features = ["serde"], default-features = false }
memmap2 = "0.9.4"
postcard = { version = "1.0.8", features = ["use-std"] }
roxmltree = { version = "0.19.0", features = ["std"], default-features = false }
serde = { version = "1.0.202", features = ["derive"] }
smallvec = { version = "1.13.2", features = ["serde"] }
strum = { version = "0.26.2", features = ["derive", "phf"] }
