[workspace]
members = ["./code/jdict-shared/", "./code/jdict-server/", "./code/jdict-egui/"]
resolver = "2"

[profile.dev.package."*"]
opt-level = 3

[profile.dev.package."jdict-shared"]
opt-level = 3
debug = 1

[profile.release]
opt-level = 3
lto = "fat"
panic = "abort"
