[workspace]
members = [
    "./code/jdict-shared/",
    "./code/jdict-server/",
    "./code/jdict-tauri/",
	"./code/jdict-egui/",
]

[profile.dev.package."*"]
opt-level = 3

[profile.dev.package."jdict-shared"]
opt-level = 3

[profile.release]
opt-level = 3
lto = "fat"
panic = "abort"
