fn snip_prefix(prefix: &str, text: &mut &str) -> bool {
    if let Some(s) = text.strip_prefix(prefix) {
        *text = s;
        true
    } else {
        false
    }
}

fn remove_first_char(text: &mut &str) -> Option<char> {
    let mut chars = text.chars();
    let c = chars.next()?;
    *text = chars.as_str();
    Some(c)
}

pub fn to_romaji(text: &str) -> String {
    let mut result = String::new();
    let mut text_copy = text;
    while !text_copy.is_empty() {
        if      snip_prefix("きゃ", &mut text_copy) { result.push_str("kya"); }
        else if snip_prefix("きゅ", &mut text_copy) { result.push_str("kyu"); }
        else if snip_prefix("きょ", &mut text_copy) { result.push_str("kyo"); }
        else if snip_prefix("しゃ", &mut text_copy) { result.push_str("sha"); }
        else if snip_prefix("しゅ", &mut text_copy) { result.push_str("shu"); }
        else if snip_prefix("しょ", &mut text_copy) { result.push_str("sho"); }
        else if snip_prefix("ちゃ", &mut text_copy) { result.push_str("cha"); }
        else if snip_prefix("ちゅ", &mut text_copy) { result.push_str("chu"); }
        else if snip_prefix("ちょ", &mut text_copy) { result.push_str("cho"); }
        else if snip_prefix("にゃ", &mut text_copy) { result.push_str("nya"); }
        else if snip_prefix("にゅ", &mut text_copy) { result.push_str("nyu"); }
        else if snip_prefix("にょ", &mut text_copy) { result.push_str("nyo"); }
        else if snip_prefix("ひゃ", &mut text_copy) { result.push_str("hya"); }
        else if snip_prefix("ひゅ", &mut text_copy) { result.push_str("hyu"); }
        else if snip_prefix("ひょ", &mut text_copy) { result.push_str("hyo"); }
        else if snip_prefix("みゃ", &mut text_copy) { result.push_str("mya"); }
        else if snip_prefix("みゅ", &mut text_copy) { result.push_str("myu"); }
        else if snip_prefix("みょ", &mut text_copy) { result.push_str("myo"); }
        else if snip_prefix("りゃ", &mut text_copy) { result.push_str("rya"); }
        else if snip_prefix("りゅ", &mut text_copy) { result.push_str("ryu"); }
        else if snip_prefix("りょ", &mut text_copy) { result.push_str("ryo"); }
        else if snip_prefix("ぎゃ", &mut text_copy) { result.push_str("gya"); }
        else if snip_prefix("ぎゅ", &mut text_copy) { result.push_str("gyu"); }
        else if snip_prefix("ぎょ", &mut text_copy) { result.push_str("gyo"); }
        else if snip_prefix("じゃ", &mut text_copy) { result.push_str("ja"); }
        else if snip_prefix("じゅ", &mut text_copy) { result.push_str("ju"); }
        else if snip_prefix("じょ", &mut text_copy) { result.push_str("jo"); }
        else if snip_prefix("ぢゃ", &mut text_copy) { result.push_str("ja"); }
        else if snip_prefix("ぢゅ", &mut text_copy) { result.push_str("ju"); }
        else if snip_prefix("ぢょ", &mut text_copy) { result.push_str("jo"); }
        else if snip_prefix("びゃ", &mut text_copy) { result.push_str("bya"); }
        else if snip_prefix("びゅ", &mut text_copy) { result.push_str("byu"); }
        else if snip_prefix("びょ", &mut text_copy) { result.push_str("byo"); }
        else if snip_prefix("ぴゃ", &mut text_copy) { result.push_str("pya"); }
        else if snip_prefix("ぴゅ", &mut text_copy) { result.push_str("pyu"); }
        else if snip_prefix("ぴょ", &mut text_copy) { result.push_str("pyo"); }
        else if snip_prefix("ふぁ", &mut text_copy) { result.push_str("fa"); }
        else if snip_prefix("ふぃ", &mut text_copy) { result.push_str("fi"); }
        else if snip_prefix("ふぇ", &mut text_copy) { result.push_str("fe"); }
        else if snip_prefix("ふぉ", &mut text_copy) { result.push_str("fo"); }
        else if snip_prefix("うぃ", &mut text_copy) { result.push_str("wi"); }
        else if snip_prefix("うぇ", &mut text_copy) { result.push_str("we"); }
        else if snip_prefix("うぉ", &mut text_copy) { result.push_str("wo"); }
        else if snip_prefix("きぇ", &mut text_copy) { result.push_str("kye"); }
        else if snip_prefix("しぇ", &mut text_copy) { result.push_str("she"); }
        else if snip_prefix("ちぇ", &mut text_copy) { result.push_str("che"); }
        else if snip_prefix("にぇ", &mut text_copy) { result.push_str("nye"); }
        else if snip_prefix("ひぇ", &mut text_copy) { result.push_str("hye"); }
        else if snip_prefix("みぇ", &mut text_copy) { result.push_str("mye"); }
        else if snip_prefix("りぇ", &mut text_copy) { result.push_str("rye"); }
        else if snip_prefix("ぎぇ", &mut text_copy) { result.push_str("gye"); }
        else if snip_prefix("じぇ", &mut text_copy) { result.push_str("je"); }
        else if snip_prefix("ぢぇ", &mut text_copy) { result.push_str("je"); }
        else if snip_prefix("びぇ", &mut text_copy) { result.push_str("bye"); }
        else if snip_prefix("ぴぇ", &mut text_copy) { result.push_str("pye"); }
        else if snip_prefix("ふぇ", &mut text_copy) { result.push_str("fe"); }
        else if snip_prefix("ふぉ", &mut text_copy) { result.push_str("fo"); }
        else if snip_prefix("きゃ", &mut text_copy) { result.push_str("kya"); }
        else if snip_prefix("きゅ", &mut text_copy) { result.push_str("kyu"); }
        else if snip_prefix("きょ", &mut text_copy) { result.push_str("kyo"); }
        else if snip_prefix("しゃ", &mut text_copy) { result.push_str("sha"); }
        else if snip_prefix("しゅ", &mut text_copy) { result.push_str("shu"); }
        else if snip_prefix("しょ", &mut text_copy) { result.push_str("sho"); }
        else if snip_prefix("ちゃ", &mut text_copy) { result.push_str("cha"); }
        else if snip_prefix("ちゅ", &mut text_copy) { result.push_str("chu"); }
        else if snip_prefix("ちょ", &mut text_copy) { result.push_str("cho"); }
        else if snip_prefix("にゃ", &mut text_copy) { result.push_str("nya"); }
        else if snip_prefix("にゅ", &mut text_copy) { result.push_str("nyu"); }
        else if snip_prefix("にょ", &mut text_copy) { result.push_str("nyo"); }
        else if snip_prefix("ひゃ", &mut text_copy) { result.push_str("hya"); }
        else if snip_prefix("ひゅ", &mut text_copy) { result.push_str("hyu"); }
        else if snip_prefix("ひょ", &mut text_copy) { result.push_str("hyo"); }
        else if snip_prefix("みゃ", &mut text_copy) { result.push_str("mya"); }
        else if snip_prefix("みゅ", &mut text_copy) { result.push_str("myu"); }
        else if snip_prefix("みょ", &mut text_copy) { result.push_str("myo"); }
        else if snip_prefix("りゃ", &mut text_copy) { result.push_str("rya"); }
        else if snip_prefix("りゅ", &mut text_copy) { result.push_str("ryu"); }
        else if snip_prefix("りょ", &mut text_copy) { result.push_str("ryo"); }
        else if snip_prefix("ぎゃ", &mut text_copy) { result.push_str("gya"); }
        else if snip_prefix("ぎゅ", &mut text_copy) { result.push_str("gyu"); }
        else if snip_prefix("ぎょ", &mut text_copy) { result.push_str("gyo"); }
        else if snip_prefix("じゃ", &mut text_copy) { result.push_str("ja"); }
        else if snip_prefix("じゅ", &mut text_copy) { result.push_str("ju"); }
        else if snip_prefix("じょ", &mut text_copy) { result.push_str("jo"); }
        else if snip_prefix("ぢゃ", &mut text_copy) { result.push_str("ja"); }
        else if snip_prefix("ぢゅ", &mut text_copy) { result.push_str("ju"); }
        else if snip_prefix("ぢょ", &mut text_copy) { result.push_str("jo"); }
        else if snip_prefix("びゃ", &mut text_copy) { result.push_str("bya"); }
        else if snip_prefix("びゅ", &mut text_copy) { result.push_str("byu"); }
        else if snip_prefix("びょ", &mut text_copy) { result.push_str("byo"); }
        else if snip_prefix("ぴゃ", &mut text_copy) { result.push_str("pya"); }
        else if snip_prefix("ぴゅ", &mut text_copy) { result.push_str("pyu"); }
        else if snip_prefix("ぴょ", &mut text_copy) { result.push_str("pyo"); }
        else if snip_prefix("あ", &mut text_copy) { result.push_str("a"); }
        else if snip_prefix("い", &mut text_copy) { result.push_str("i"); }
        else if snip_prefix("う", &mut text_copy) { result.push_str("u"); }
        else if snip_prefix("え", &mut text_copy) { result.push_str("e"); }
        else if snip_prefix("お", &mut text_copy) { result.push_str("o"); }
        else if snip_prefix("か", &mut text_copy) { result.push_str("ka"); }
        else if snip_prefix("き", &mut text_copy) { result.push_str("ki"); }
        else if snip_prefix("く", &mut text_copy) { result.push_str("ku"); }
        else if snip_prefix("け", &mut text_copy) { result.push_str("ke"); }
        else if snip_prefix("こ", &mut text_copy) { result.push_str("ko"); }
        else if snip_prefix("さ", &mut text_copy) { result.push_str("sa"); }
        else if snip_prefix("し", &mut text_copy) { result.push_str("shi"); }
        else if snip_prefix("す", &mut text_copy) { result.push_str("su"); }
        else if snip_prefix("せ", &mut text_copy) { result.push_str("se"); }
        else if snip_prefix("そ", &mut text_copy) { result.push_str("so"); }
        else if snip_prefix("た", &mut text_copy) { result.push_str("ta"); }
        else if snip_prefix("ち", &mut text_copy) { result.push_str("chi"); }
        else if snip_prefix("つ", &mut text_copy) { result.push_str("tsu"); }
        else if snip_prefix("て", &mut text_copy) { result.push_str("te"); }
        else if snip_prefix("と", &mut text_copy) { result.push_str("to"); }
        else if snip_prefix("な", &mut text_copy) { result.push_str("na"); }
        else if snip_prefix("に", &mut text_copy) { result.push_str("ni"); }
        else if snip_prefix("ぬ", &mut text_copy) { result.push_str("nu"); }
        else if snip_prefix("ね", &mut text_copy) { result.push_str("ne"); }
        else if snip_prefix("の", &mut text_copy) { result.push_str("no"); }
        else if snip_prefix("は", &mut text_copy) { result.push_str("ha"); }
        else if snip_prefix("ひ", &mut text_copy) { result.push_str("hi"); }
        else if snip_prefix("ふ", &mut text_copy) { result.push_str("fu"); }
        else if snip_prefix("へ", &mut text_copy) { result.push_str("he"); }
        else if snip_prefix("ほ", &mut text_copy) { result.push_str("ho"); }
        else if snip_prefix("ま", &mut text_copy) { result.push_str("ma"); }
        else if snip_prefix("み", &mut text_copy) { result.push_str("mi"); }
        else if snip_prefix("む", &mut text_copy) { result.push_str("mu"); }
        else if snip_prefix("め", &mut text_copy) { result.push_str("me"); }
        else if snip_prefix("も", &mut text_copy) { result.push_str("mo"); }
        else if snip_prefix("や", &mut text_copy) { result.push_str("ya"); }
        else if snip_prefix("ゆ", &mut text_copy) { result.push_str("yu"); }
        else if snip_prefix("よ", &mut text_copy) { result.push_str("yo"); }
        else if snip_prefix("ら", &mut text_copy) { result.push_str("ra"); }
        else if snip_prefix("り", &mut text_copy) { result.push_str("ri"); }
        else if snip_prefix("る", &mut text_copy) { result.push_str("ru"); }
        else if snip_prefix("れ", &mut text_copy) { result.push_str("re"); }
        else if snip_prefix("ろ", &mut text_copy) { result.push_str("ro"); }
        else if snip_prefix("わ", &mut text_copy) { result.push_str("wa"); }
        else if snip_prefix("を", &mut text_copy) { result.push_str("wo"); }
        else if snip_prefix("ん", &mut text_copy) { result.push_str("n"); }
        else if snip_prefix("が", &mut text_copy) { result.push_str("ga"); }
        else if snip_prefix("ぎ", &mut text_copy) { result.push_str("gi"); }
        else if snip_prefix("ぐ", &mut text_copy) { result.push_str("gu"); }
        else if snip_prefix("げ", &mut text_copy) { result.push_str("ge"); }
        else if snip_prefix("ご", &mut text_copy) { result.push_str("go"); }
        else if snip_prefix("ざ", &mut text_copy) { result.push_str("za"); }
        else if snip_prefix("じ", &mut text_copy) { result.push_str("ji"); }
        else if snip_prefix("ず", &mut text_copy) { result.push_str("zu"); }
        else if snip_prefix("ぜ", &mut text_copy) { result.push_str("ze"); }
        else if snip_prefix("ぞ", &mut text_copy) { result.push_str("zo"); }
        else if snip_prefix("だ", &mut text_copy) { result.push_str("da"); }
        else if snip_prefix("ぢ", &mut text_copy) { result.push_str("ji"); }
        else if snip_prefix("づ", &mut text_copy) { result.push_str("zu"); }
        else if snip_prefix("で", &mut text_copy) { result.push_str("de"); }
        else if snip_prefix("ど", &mut text_copy) { result.push_str("do"); }
        else if snip_prefix("ば", &mut text_copy) { result.push_str("ba"); }
        else if snip_prefix("び", &mut text_copy) { result.push_str("bi"); }
        else if snip_prefix("ぶ", &mut text_copy) { result.push_str("bu"); }
        else if snip_prefix("べ", &mut text_copy) { result.push_str("be"); }
        else if snip_prefix("ぼ", &mut text_copy) { result.push_str("bo"); }
        else if snip_prefix("ぱ", &mut text_copy) { result.push_str("pa"); }
        else if snip_prefix("ぴ", &mut text_copy) { result.push_str("pi"); }
        else if snip_prefix("ぷ", &mut text_copy) { result.push_str("pu"); }
        else if snip_prefix("ぺ", &mut text_copy) { result.push_str("pe"); }
        else if snip_prefix("ぽ", &mut text_copy) { result.push_str("po"); }
        else if snip_prefix("ヴァ", &mut text_copy) { result.push_str("va"); }
        else if snip_prefix("ヴィ", &mut text_copy) { result.push_str("vi"); }
        else if snip_prefix("ヴ", &mut text_copy) { result.push_str("vu"); }
        else if snip_prefix("ヴェ", &mut text_copy) { result.push_str("ve"); }
        else if snip_prefix("ヴォ", &mut text_copy) { result.push_str("vo"); }
        else if snip_prefix("う゛ぁ", &mut text_copy) { result.push_str("va"); }
        else if snip_prefix("う゛ぃ", &mut text_copy) { result.push_str("vi"); }
        else if snip_prefix("う゛", &mut text_copy) { result.push_str("vu"); }
        else if snip_prefix("う゛ぇ", &mut text_copy) { result.push_str("ve"); }
        else if snip_prefix("う゛ぉ", &mut text_copy) { result.push_str("vo"); }
        else if snip_prefix("キャ", &mut text_copy) { result.push_str("kya"); }
        else if snip_prefix("キュ", &mut text_copy) { result.push_str("kyu"); }
        else if snip_prefix("キョ", &mut text_copy) { result.push_str("kyo"); }
        else if snip_prefix("シャ", &mut text_copy) { result.push_str("sha"); }
        else if snip_prefix("シュ", &mut text_copy) { result.push_str("shu"); }
        else if snip_prefix("ショ", &mut text_copy) { result.push_str("sho"); }
        else if snip_prefix("チャ", &mut text_copy) { result.push_str("cha"); }
        else if snip_prefix("チュ", &mut text_copy) { result.push_str("chu"); }
        else if snip_prefix("チョ", &mut text_copy) { result.push_str("cho"); }
        else if snip_prefix("ニャ", &mut text_copy) { result.push_str("nya"); }
        else if snip_prefix("ニュ", &mut text_copy) { result.push_str("nyu"); }
        else if snip_prefix("ニョ", &mut text_copy) { result.push_str("nyo"); }
        else if snip_prefix("ヒャ", &mut text_copy) { result.push_str("hya"); }
        else if snip_prefix("ヒュ", &mut text_copy) { result.push_str("hyu"); }
        else if snip_prefix("ヒョ", &mut text_copy) { result.push_str("hyo"); }
        else if snip_prefix("ミャ", &mut text_copy) { result.push_str("mya"); }
        else if snip_prefix("ミュ", &mut text_copy) { result.push_str("myu"); }
        else if snip_prefix("ミョ", &mut text_copy) { result.push_str("myo"); }
        else if snip_prefix("リャ", &mut text_copy) { result.push_str("rya"); }
        else if snip_prefix("リュ", &mut text_copy) { result.push_str("ryu"); }
        else if snip_prefix("リョ", &mut text_copy) { result.push_str("ryo"); }
        else if snip_prefix("ギャ", &mut text_copy) { result.push_str("gya"); }
        else if snip_prefix("ギュ", &mut text_copy) { result.push_str("gyu"); }
        else if snip_prefix("ギョ", &mut text_copy) { result.push_str("gyo"); }
        else if snip_prefix("ジャ", &mut text_copy) { result.push_str("ja"); }
        else if snip_prefix("ジュ", &mut text_copy) { result.push_str("ju"); }
        else if snip_prefix("ジョ", &mut text_copy) { result.push_str("jo"); }
        else if snip_prefix("ヂャ", &mut text_copy) { result.push_str("ja"); }
        else if snip_prefix("ヂュ", &mut text_copy) { result.push_str("ju"); }
        else if snip_prefix("ヂョ", &mut text_copy) { result.push_str("jo"); }
        else if snip_prefix("ビャ", &mut text_copy) { result.push_str("bya"); }
        else if snip_prefix("ビュ", &mut text_copy) { result.push_str("byu"); }
        else if snip_prefix("ビョ", &mut text_copy) { result.push_str("byo"); }
        else if snip_prefix("ピャ", &mut text_copy) { result.push_str("pya"); }
        else if snip_prefix("ピュ", &mut text_copy) { result.push_str("pyu"); }
        else if snip_prefix("ピョ", &mut text_copy) { result.push_str("pyo"); }
        else if snip_prefix("ヴァ", &mut text_copy) { result.push_str("va"); }
        else if snip_prefix("ヴィ", &mut text_copy) { result.push_str("vi"); }
        else if snip_prefix("ヴ", &mut text_copy) { result.push_str("vu"); }
        else if snip_prefix("ヴェ", &mut text_copy) { result.push_str("ve"); }
        else if snip_prefix("ヴォ", &mut text_copy) { result.push_str("vo"); }
        else if snip_prefix("ウ゛ァ", &mut text_copy) { result.push_str("va"); }
        else if snip_prefix("ウ゛ィ", &mut text_copy) { result.push_str("vi"); }
        else if snip_prefix("ウ゛", &mut text_copy) { result.push_str("vu"); }
        else if snip_prefix("ウ゛ェ", &mut text_copy) { result.push_str("ve"); }
        else if snip_prefix("ウ゛ォ", &mut text_copy) { result.push_str("vo"); }
        else if snip_prefix("キャ", &mut text_copy) { result.push_str("kya"); }
        else if snip_prefix("キュ", &mut text_copy) { result.push_str("kyu"); }
        else if snip_prefix("キョ", &mut text_copy) { result.push_str("kyo"); }
        else if snip_prefix("シャ", &mut text_copy) { result.push_str("sha"); }
        else if snip_prefix("シュ", &mut text_copy) { result.push_str("shu"); }
        else if snip_prefix("ショ", &mut text_copy) { result.push_str("sho"); }
        else if snip_prefix("チャ", &mut text_copy) { result.push_str("cha"); }
        else if snip_prefix("チュ", &mut text_copy) { result.push_str("chu"); }
        else if snip_prefix("チョ", &mut text_copy) { result.push_str("cho"); }
        else if snip_prefix("ニャ", &mut text_copy) { result.push_str("nya"); }
        else if snip_prefix("ニュ", &mut text_copy) { result.push_str("nyu"); }
        else if snip_prefix("ニョ", &mut text_copy) { result.push_str("nyo"); }
        else if snip_prefix("ヒャ", &mut text_copy) { result.push_str("hya"); }
        else if snip_prefix("ヒュ", &mut text_copy) { result.push_str("hyu"); }
        else if snip_prefix("ヒョ", &mut text_copy) { result.push_str("hyo"); }
        else if snip_prefix("ミャ", &mut text_copy) { result.push_str("mya"); }
        else if snip_prefix("ミュ", &mut text_copy) { result.push_str("myu"); }
        else if snip_prefix("ミョ", &mut text_copy) { result.push_str("myo"); }
        else if snip_prefix("リャ", &mut text_copy) { result.push_str("rya"); }
        else if snip_prefix("リュ", &mut text_copy) { result.push_str("ryu"); }
        else if snip_prefix("リョ", &mut text_copy) { result.push_str("ryo"); }
        else if snip_prefix("ギャ", &mut text_copy) { result.push_str("gya"); }
        else if snip_prefix("ギュ", &mut text_copy) { result.push_str("gyu"); }
        else if snip_prefix("ギョ", &mut text_copy) { result.push_str("gyo"); }
        else if snip_prefix("ジャ", &mut text_copy) { result.push_str("ja"); }
        else if snip_prefix("ジュ", &mut text_copy) { result.push_str("ju"); }
        else if snip_prefix("ジョ", &mut text_copy) { result.push_str("jo"); }
        else if snip_prefix("ヂャ", &mut text_copy) { result.push_str("ja"); }
        else if snip_prefix("ヂュ", &mut text_copy) { result.push_str("ju"); }
        else if snip_prefix("ヂョ", &mut text_copy) { result.push_str("jo"); }
        else if snip_prefix("ビャ", &mut text_copy) { result.push_str("bya"); }
        else if snip_prefix("ビュ", &mut text_copy) { result.push_str("byu"); }
        else if snip_prefix("ビョ", &mut text_copy) { result.push_str("byo"); }
        else if snip_prefix("ピャ", &mut text_copy) { result.push_str("pya"); }
        else if snip_prefix("ピュ", &mut text_copy) { result.push_str("pyu"); }
        else if snip_prefix("ピョ", &mut text_copy) { result.push_str("pyo"); }
        else if snip_prefix("ヴァ", &mut text_copy) { result.push_str("va"); }
        else if snip_prefix("ヴィ", &mut text_copy) { result.push_str("vi"); }
        else if snip_prefix("ヴ", &mut text_copy) { result.push_str("vu"); }
        else if snip_prefix("ヴェ", &mut text_copy) { result.push_str("ve"); }
        else if snip_prefix("ヴォ", &mut text_copy) { result.push_str("vo"); }
        else if snip_prefix("ウ゛ァ", &mut text_copy) { result.push_str("va"); }
        else if snip_prefix("ウ゛ィ", &mut text_copy) { result.push_str("vi"); }
        else if snip_prefix("ウ゛", &mut text_copy) { result.push_str("vu"); }
        else if snip_prefix("ウ゛ェ", &mut text_copy) { result.push_str("ve"); }
        else if snip_prefix("ウ゛ォ", &mut text_copy) { result.push_str("vo"); }
        else if snip_prefix("キャ", &mut text_copy) { result.push_str("kya"); }
        else if snip_prefix("キュ", &mut text_copy) { result.push_str("kyu"); }
        else if snip_prefix("キョ", &mut text_copy) { result.push_str("kyo"); }
        else if snip_prefix("シャ", &mut text_copy) { result.push_str("sha"); }
        else if snip_prefix("シュ", &mut text_copy) { result.push_str("shu"); }
        else if snip_prefix("ショ", &mut text_copy) { result.push_str("sho"); }
        else if snip_prefix("チャ", &mut text_copy) { result.push_str("cha"); }
        else if snip_prefix("チュ", &mut text_copy) { result.push_str("chu"); }
        else if snip_prefix("チョ", &mut text_copy) { result.push_str("cho"); }
        else if snip_prefix("ニャ", &mut text_copy) { result.push_str("nya"); }
        else if snip_prefix("ニュ", &mut text_copy) { result.push_str("nyu"); }
        else if snip_prefix("ニョ", &mut text_copy) { result.push_str("nyo"); }
        else if snip_prefix("ヒャ", &mut text_copy) { result.push_str("hya"); }
        else if snip_prefix("ヒュ", &mut text_copy) { result.push_str("hyu"); }
        else if snip_prefix("ヒョ", &mut text_copy) { result.push_str("hyo"); }
        else if snip_prefix("ミャ", &mut text_copy) { result.push_str("mya"); }
        else if snip_prefix("ミュ", &mut text_copy) { result.push_str("myu"); }
        else if snip_prefix("ミョ", &mut text_copy) { result.push_str("myo"); }
        else if snip_prefix("リャ", &mut text_copy) { result.push_str("rya"); }
        else if snip_prefix("リュ", &mut text_copy) { result.push_str("ryu"); }
        else if snip_prefix("リョ", &mut text_copy) { result.push_str("ryo"); }
        else if snip_prefix("ギャ", &mut text_copy) { result.push_str("gya"); }
        else if snip_prefix("ギュ", &mut text_copy) { result.push_str("gyu"); }
        else if snip_prefix("ギョ", &mut text_copy) { result.push_str("gyo"); }
        else if snip_prefix("ジャ", &mut text_copy) { result.push_str("ja"); }
        else if snip_prefix("ジュ", &mut text_copy) { result.push_str("ju"); }
        else if snip_prefix("ジョ", &mut text_copy) { result.push_str("jo"); }
        else if snip_prefix("ヂャ", &mut text_copy) { result.push_str("ja"); }
        else if snip_prefix("ヂュ", &mut text_copy) { result.push_str("ju"); }
        else if snip_prefix("ヂョ", &mut text_copy) { result.push_str("jo"); }
        else if snip_prefix("ビャ", &mut text_copy) { result.push_str("bya"); }
        else if snip_prefix("ビュ", &mut text_copy) { result.push_str("byu"); }
        else if snip_prefix("ビョ", &mut text_copy) { result.push_str("byo"); }
        else if snip_prefix("ピャ", &mut text_copy) { result.push_str("pya"); }
        else if snip_prefix("ピュ", &mut text_copy) { result.push_str("pyu"); }
        else if snip_prefix("ピョ", &mut text_copy) { result.push_str("pyo"); }
        else if snip_prefix("ヴァ", &mut text_copy) { result.push_str("va"); }
        else if snip_prefix("ヴィ", &mut text_copy) { result.push_str("vi"); }
        else if snip_prefix("ヴ", &mut text_copy) { result.push_str("vu"); }
        else if snip_prefix("ヴェ", &mut text_copy) { result.push_str("ve"); }
        else if snip_prefix("ヴォ", &mut text_copy) { result.push_str("vo"); }
        else if snip_prefix("ウ゛ァ", &mut text_copy) { result.push_str("va"); }
        else if snip_prefix("ウ゛ィ", &mut text_copy) { result.push_str("vi"); }
        else if snip_prefix("ウ゛", &mut text_copy) { result.push_str("vu"); }
        else if snip_prefix("ウ゛ェ", &mut text_copy) { result.push_str("ve"); }
        else if snip_prefix("ウ゛ォ", &mut text_copy) { result.push_str("vo"); }
        else if snip_prefix("ア", &mut text_copy) { result.push_str("a"); }
        else if snip_prefix("イ", &mut text_copy) { result.push_str("i"); }
        else if snip_prefix("ウ", &mut text_copy) { result.push_str("u"); }
        else if snip_prefix("エ", &mut text_copy) { result.push_str("e"); }
        else if snip_prefix("オ", &mut text_copy) { result.push_str("o"); }
        else if snip_prefix("カ", &mut text_copy) { result.push_str("ka"); }
        else if snip_prefix("キ", &mut text_copy) { result.push_str("ki"); }
        else if snip_prefix("ク", &mut text_copy) { result.push_str("ku"); }
        else if snip_prefix("ケ", &mut text_copy) { result.push_str("ke"); }
        else if snip_prefix("コ", &mut text_copy) { result.push_str("ko"); }
        else if snip_prefix("サ", &mut text_copy) { result.push_str("sa"); }
        else if snip_prefix("シ", &mut text_copy) { result.push_str("shi"); }
        else if snip_prefix("ス", &mut text_copy) { result.push_str("su"); }
        else if snip_prefix("セ", &mut text_copy) { result.push_str("se"); }
        else if snip_prefix("ソ", &mut text_copy) { result.push_str("so"); }
        else if snip_prefix("タ", &mut text_copy) { result.push_str("ta"); }
        else if snip_prefix("チ", &mut text_copy) { result.push_str("chi"); }
        else if snip_prefix("ツ", &mut text_copy) { result.push_str("tsu"); }
        else if snip_prefix("テ", &mut text_copy) { result.push_str("te"); }
        else if snip_prefix("ト", &mut text_copy) { result.push_str("to"); }
        else if snip_prefix("ナ", &mut text_copy) { result.push_str("na"); }
        else if snip_prefix("ニ", &mut text_copy) { result.push_str("ni"); }
        else if snip_prefix("ヌ", &mut text_copy) { result.push_str("nu"); }
        else if snip_prefix("ネ", &mut text_copy) { result.push_str("ne"); }
        else if snip_prefix("ノ", &mut text_copy) { result.push_str("no"); }
        else if snip_prefix("ハ", &mut text_copy) { result.push_str("ha"); }
        else if snip_prefix("ヒ", &mut text_copy) { result.push_str("hi"); }
        else if snip_prefix("フ", &mut text_copy) { result.push_str("fu"); }
        else if snip_prefix("ヘ", &mut text_copy) { result.push_str("he"); }
        else if snip_prefix("ホ", &mut text_copy) { result.push_str("ho"); }
        else if snip_prefix("マ", &mut text_copy) { result.push_str("ma"); }
        else if snip_prefix("ミ", &mut text_copy) { result.push_str("mi"); }
        else if snip_prefix("ム", &mut text_copy) { result.push_str("mu"); }
        else if snip_prefix("メ", &mut text_copy) { result.push_str("me"); }
        else if snip_prefix("モ", &mut text_copy) { result.push_str("mo"); }
        else if snip_prefix("ヤ", &mut text_copy) { result.push_str("ya"); }
        else if snip_prefix("ユ", &mut text_copy) { result.push_str("yu"); }
        else if snip_prefix("ヨ", &mut text_copy) { result.push_str("yo"); }
        else if snip_prefix("ラ", &mut text_copy) { result.push_str("ra"); }
        else if snip_prefix("リ", &mut text_copy) { result.push_str("ri"); }
        else if snip_prefix("ル", &mut text_copy) { result.push_str("ru"); }
        else if snip_prefix("レ", &mut text_copy) { result.push_str("re"); }
        else if snip_prefix("ロ", &mut text_copy) { result.push_str("ro"); }
        else if snip_prefix("ワ", &mut text_copy) { result.push_str("wa"); }
        else if snip_prefix("ヲ", &mut text_copy) { result.push_str("wo"); }
        else if snip_prefix("ン", &mut text_copy) { result.push_str("n"); }
        else if snip_prefix("ガ", &mut text_copy) { result.push_str("ga"); }
        else if snip_prefix("ギ", &mut text_copy) { result.push_str("gi"); }
        else if snip_prefix("グ", &mut text_copy) { result.push_str("gu"); }
        else if snip_prefix("ゲ", &mut text_copy) { result.push_str("ge"); }
        else if snip_prefix("ゴ", &mut text_copy) { result.push_str("go"); }
        else if snip_prefix("ザ", &mut text_copy) { result.push_str("za"); }
        else if snip_prefix("ジ", &mut text_copy) { result.push_str("ji"); }
        else if snip_prefix("ズ", &mut text_copy) { result.push_str("zu"); }
        else if snip_prefix("ゼ", &mut text_copy) { result.push_str("ze"); }
        else if snip_prefix("ゾ", &mut text_copy) { result.push_str("zo"); }
        else if snip_prefix("ダ", &mut text_copy) { result.push_str("da"); }
        else if snip_prefix("ヂ", &mut text_copy) { result.push_str("ji"); }
        else if snip_prefix("ヅ", &mut text_copy) { result.push_str("zu"); }
        else if snip_prefix("デ", &mut text_copy) { result.push_str("de"); }
        else if snip_prefix("ド", &mut text_copy) { result.push_str("do"); }
        else if snip_prefix("バ", &mut text_copy) { result.push_str("ba"); }
        else if snip_prefix("ビ", &mut text_copy) { result.push_str("bi"); }
        else if snip_prefix("ブ", &mut text_copy) { result.push_str("bu"); }
        else if snip_prefix("ベ", &mut text_copy) { result.push_str("be"); }
        else if snip_prefix("ボ", &mut text_copy) { result.push_str("bo"); }
        else if snip_prefix("パ", &mut text_copy) { result.push_str("pa"); }
        else if snip_prefix("ピ", &mut text_copy) { result.push_str("pi"); }
        else if snip_prefix("プ", &mut text_copy) { result.push_str("pu"); }
        else if snip_prefix("ペ", &mut text_copy) { result.push_str("pe"); }
        else if snip_prefix("ポ", &mut text_copy) { result.push_str("po"); }
        else if snip_prefix("ァ", &mut text_copy) { result.push_str("a"); }
        else if snip_prefix("ィ", &mut text_copy) { result.push_str("i"); }
        else if snip_prefix("ゥ", &mut text_copy) { result.push_str("u"); }
        else if snip_prefix("ェ", &mut text_copy) { result.push_str("e"); }
        else if snip_prefix("ォ", &mut text_copy) { result.push_str("o"); }
        else if snip_prefix("ャ", &mut text_copy) { result.push_str("ya"); }
        else if snip_prefix("ュ", &mut text_copy) { result.push_str("yu"); }
        else if snip_prefix("ョ", &mut text_copy) { result.push_str("yo"); }
        else if snip_prefix("ッ", &mut text_copy) { result.push_str("tu"); }
        else if snip_prefix("ヴ", &mut text_copy) { result.push_str("vu"); }
        else if snip_prefix("ー", &mut text_copy) { result.push_str("-"); }
        else if snip_prefix("。", &mut text_copy) { result.push_str("."); }
        else if snip_prefix("、", &mut text_copy) { result.push_str(","); }
        else if snip_prefix("！", &mut text_copy) { result.push_str("!"); }
        else if snip_prefix("？", &mut text_copy) { result.push_str("?"); }
        else if snip_prefix("　", &mut text_copy) { result.push_str(" "); }
        else {
            // Strip first char from text_copy and push it to result
            result.push(remove_first_char(&mut text_copy).unwrap());
        }
    }
    result
}
