[package]
name = "jdict-egui"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.26.0"
egui = "0.26.0"
itertools = "0.12.1"
jdict-shared = { version = "0.1.0", path = "../jdict-shared" }
svgtypes = "0.14.0"
